# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  peer0.org1.example.com:
    hostname: peer0.org1.example.com
    network_mode: "host"
    container_name: peer0.org1.example.com
    extends:
      file: ../../base/docker-compose-base.yaml
      service: peer0.org1.example.com
