---

application:
  local: true
  cpus: 2
  orderers:
    - name: orderer
      host: orderer.example.com
      port: 7050
  ordererMsp: OrdererMSP
  channels:
    - mychannel
  tlsEnabled: true
  reqTimeout: 120
